[[cluster-state]]
== 集群状态

集群状态API允许用户获取整个集群的综合状态信息。

[source,js]
--------------------------------------------------
GET /_cluster/state
--------------------------------------------------
// CONSOLE

响应将会返回集群的名称，整个集群状态的压缩大小（集群状态为了在网络上传输进行序列化之后的大小），和集群状态本身。整个返回值可以像下文描述的一样进行过滤，只获取需要的部分。

默认情况下，集群状态API会作用在集群主节点上以保证返回的集群状态是最新的。为了debug，你可以通过在查询字符串中添加 `local=true` 设置从特定的节点获取本地集群状态。

[float]
=== 响应过滤

由于集群的状态是可增长的（取决于分片和索引的数量，用户的映射和索引），可以通过设定URL中的特殊部分来过滤集群状态API的响应结果。

[source,js]
--------------------------------------------------
GET /_cluster/state/{metrics}/{indices}
--------------------------------------------------
// CONSOLE

`metrics` 可以是由逗号分隔的以下标签的列表

`version`::
    展示集群状态版本。

`master_node`::
    展示响应中的给定 `master_node` 部分。 

`nodes`::
    展示响应中的 `nodes` 部分。

`routing_table`::
    展示响应中的 `routing_table` 部分。如果你提供一个逗号分隔的索引的列表，那么返回结果将只包含列表中的索引。

`metadata`::
    展示响应中的 `metadata` 数据。如果你提供一个逗号分隔的索引列表，那么返回结果将只包含列表中的索引。

`blocks`::
    展示响应中的 `blocks` 部分。

下面这个例子将会返回只有 `foo` 和 `bar` 索引下的 `metadata` 和 `routing_table` 字段的数据：

[source,js]
--------------------------------------------------
GET /_cluster/state/metadata,routing_table/foo,bar
--------------------------------------------------
// CONSOLE

接下去的例子将返回 `foo` 和 `bar` 索引的所有信息数据：

[source,js]
--------------------------------------------------
GET /_cluster/state/_all/foo,bar
--------------------------------------------------
// CONSOLE

这个例子只返回 `blocks` 数据：
[source,js]
--------------------------------------------------
GET /_cluster/state/blocks
--------------------------------------------------
// CONSOLE


